---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":1259,"creation_ts":"2013-02-28 08:53:00 -0800","short_desc":"state of generator after error thrown","delta_ts":"2013-10-10 12:52:42 -0700","product":"Draft for 6th Edition","component":"technical issue","version":"All","rep_platform":"All","op_sys":"All","bug_status":"RESOLVED","resolution":"FIXED","priority":"Normal","bug_severity":"enhancement","everconfirmed":true,"reporter":{"uid":"wingo","name":"Andy Wingo"},"assigned_to":{"uid":"allen","name":"Allen Wirfs-Brock"},"long_desc":[{"commentid":3255,"comment_count":0,"who":{"uid":"wingo","name":"Andy Wingo"},"bug_when":"2013-02-28 08:53:53 -0800","thetext":"Hi,\n\nI realize the generator language hasn't landed yet in the spec, but if we take this as a reference:\n\n  http://wiki.ecmascript.org/doku.php?id=harmony:generators\n\nI think perhaps the interaction between exceptions and generator state is not quite clear.\n\nSpecifically: if a generator throws an uncaught exception, what is its state?\n\nIf a generator throws a StopIteration explicitly, what is its state?\n\nAs it is, harmony:generators suggests that the generator would be left in the \"executing\" state in both cases.  This is OK but it might merit a clarification."},{"commentid":5889,"comment_count":1,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2013-10-10 12:52:42 -0700","thetext":"this is now convered by the actual spec. language. See section 25.3.3"}]}}
---
