---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":1561,"creation_ts":"2013-06-18 05:45:00 -0700","short_desc":"Wrong error messages in test S12.6.1_A1.","delta_ts":"2014-07-10 14:32:32 -0700","product":"Test262","component":"ECMA-262 Tests","version":"unspecified","rep_platform":"All","op_sys":"All","bug_status":"RESOLVED","resolution":"FIXED","priority":"Normal","bug_severity":"enhancement","everconfirmed":true,"reporter":{"uid":"martin.bodin","name":"Martin Bodin"},"assigned_to":{"uid":"brterlso","name":"Brian Terlson"},"cc":"jaimelynschatz","long_desc":[{"commentid":4239,"comment_count":0,"who":{"uid":"martin.bodin","name":"Martin Bodin"},"bug_when":"2013-06-18 05:45:44 -0700","thetext":"Hi,\n\nI was reading the test S12.6.1_A1 and I didn’t understood it until I realize that the error messages wasn’t matching the tested property.\n\nFor instance, the test begins with:\nvar __in__do;\n\ndo __in__do=1; while ( false );\n\n//////////////////////////////////////////////////////////////////////////////\n//CHECK#1\nif (__in__do!==1) {\n\t$ERROR('#1: false evaluates to false');\n}\n\nMmmh…  If “false” doesn’t evaluate to false due to oddities of the JS interpreter, then the loop won’t terminate and this message won’t ever happen.\nI think the error message should be “$ERROR('#1:  the inner statement of a do-loop should be executed.')”.  The current one is quite ununderstandable.\n\nMartin."},{"commentid":7003,"comment_count":1,"who":{"uid":"jaimelynschatz","name":"Jaime"},"bug_when":"2014-01-26 16:25:14 -0800","thetext":"pull request submitted to Github."}]}}
---
