---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":1704,"creation_ts":"2013-08-02 05:06:00 -0700","short_desc":"Failing tests when Object.prototype is not in the proto-chain of the global object","delta_ts":"2013-08-02 05:06:18 -0700","product":"Test262","component":"ECMA-262 Tests","version":"unspecified","rep_platform":"All","op_sys":"All","bug_status":"CONFIRMED","priority":"Normal","bug_severity":"normal","everconfirmed":true,"reporter":{"uid":"andrebargull","name":"André Bargull"},"assigned_to":{"uid":"brterlso","name":"Brian Terlson"},"long_desc":[{"commentid":4718,"comment_count":0,"who":{"uid":"andrebargull","name":"André Bargull"},"bug_when":"2013-08-02 05:06:18 -0700","thetext":"This is a kind of follow-up from bug 1600. I've removed Object.prototype from the prototype chain of the global object and re-ran the test suite. The following tests did not complete successfully:\n\nS13.2.2_A19_T7\nS15.1.2.1_A4.5\nS15.1.2.2_A9.5\nS15.1.2.3_A7.5\nS15.1.2.4_A2.5\nS15.1.2.5_A2.5\nS15.1.3.1_A5.5\nS15.1.3.2_A5.5\nS15.1.3.3_A5.5\nS15.1.3.4_A5.5\n15.2.3.14-6-6\n15.2.3.2-2-30\n15.2.3.6-4-354-13\n15.2.3.6-4-354-4\n15.2.3.6-4-45\n15.2.3.6-4-531-13\n15.2.3.6-4-531-17\n15.2.3.6-4-531-4\n15.2.3.6-4-531-8\n15.2.3.6-4-538-3\n15.2.3.6-4-538-7\n15.2.3.6-4-625gs\n15.2.3.7-6-a-24\n\nMost of the time this happens because `hasOwnProperty()` or `propertyIsEnumerable` is called on the global object. But without `Object.prototype` being present in the global object's proto-chain, trying to call these functions fails at runtime. \n\nApplying the obvious workarounds should fix these problems, that means using something like `Object.prototype.hasOwnProperty.call(globalObject, 'property-name')`."}]}}
---
