---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":28,"creation_ts":"2011-02-21 10:51:00 -0800","short_desc":"S15.3.4.3_A6_T1.js is invalid (ES5 to ES5.1 change)","delta_ts":"2011-09-24 16:52:50 -0700","product":"Test262","component":"ECMA-262 Tests","version":"unspecified","rep_platform":"All","op_sys":"All","bug_status":"RESOLVED","resolution":"FIXED","bug_file_loc":"http://hg.ecmascript.org/tests/test262/rev/3990187a1534","priority":"Normal","bug_severity":"normal","everconfirmed":true,"reporter":{"uid":"dfugate","name":"Dave Fugate"},"assigned_to":{"uid":"erights","name":"Mark S. Miller"},"cc":"erights","long_desc":[{"commentid":48,"comment_count":0,"who":{"uid":"dfugate","name":"Dave Fugate"},"bug_when":"2011-02-21 10:51:58 -0800","thetext":"The test case consists of the following:\n    try {\n      Function().apply(1,{});\n      $FAIL('#1: if argArray is neither an array nor an arguments object (see 10.1.8), a TypeError exception is thrown');\n    } catch (e) {\n      if (!(e instanceof TypeError)) {\n      \t$ERROR('#1.1: if argArray is neither an array nor an arguments object (see 10.1.8), a TypeError exception is thrown');\n      }\n    }\n\nwhich expect Function.prototype.apply to fail as '{}' is not an array or arguments object.  The interesting thing here is this test was still valid up  until ES5.1 was released.  You see, ES5 still had a restriction that the second param to apply must have a 'length' property.  This restriction was removed in ES5.1 though (see steps 4 and 5 of 15.3.4.3:  ToUin32(undefined) is 0)."},{"commentid":49,"comment_count":1,"who":{"uid":"dfugate","name":"Dave Fugate"},"bug_when":"2011-02-21 10:55:17 -0800","thetext":"S15.3.4.3_A6_T4.js has the same issue."},{"commentid":466,"comment_count":2,"who":{"uid":"erights","name":"Mark S. Miller"},"bug_when":"2011-09-24 16:52:50 -0700","thetext":"Fixed at http://hg.ecmascript.org/tests/test262/rev/3990187a1534"}]}}
---
