---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":2993,"creation_ts":"2014-06-22 18:44:00 -0700","short_desc":"Store evaluation errors as \"failed\" modules","delta_ts":"2015-03-16 14:35:23 -0700","product":"Draft for 6th Edition","component":"deferred features","version":"Rev 25: May 22, 2014 Draft","rep_platform":"All","op_sys":"All","bug_status":"RESOLVED","resolution":"INVALID","priority":"Normal","bug_severity":"normal","everconfirmed":true,"reporter":{"uid":"guybedford","name":"Guy Bedford"},"assigned_to":{"uid":"allen","name":"Allen Wirfs-Brock"},"cc":["dherman","johnjbarton","jorendorff","samth"],"long_desc":[{"commentid":9061,"comment_count":0,"who":{"uid":"guybedford","name":"Guy Bedford"},"bug_when":"2014-06-22 18:44:48 -0700","thetext":"Consider the following scenario:\n\nI load two modules simultaneously - \n\nSystem.import('A').then(function() {\n  // a completed\n});\nSystem.import('B').then(function() {\n  // b completed\n});\n\nA is dependent on B. B has a runtime error in its evaluation.\n\nLinking happens fine, as in A and B are both placed in the module table linked.\n\nBut when it comes to evaluation, B is evaluated first and fails. The import promise throws. Yet its module object is still marked as evaluated due to 15.2.6.2 (7).\n\nNow A is evaluated and completes. That is, despite the evaluation failure of B it returns successfully.\n\nThat is the import promise for A completes successfully and returns the module object.\n\nPerhaps this is a feature and not a bug? It was a little surprising though."},{"commentid":9062,"comment_count":1,"who":{"uid":"samth","name":"Sam Tobin-Hochstadt [:samth]"},"bug_when":"2014-06-22 18:56:16 -0700","thetext":"This is as intended.\n\nWhile this behavior is potentially surprising, other options are worse. In particular, we can't tell what is a failure of 'B' to properly load, and what is just standard ES code execution which ends in an exception.\n\nPossible alternatives that we rejected include:\n\n- removing linked modules from the table (a very bad idea)\n- not running the code for 'A' -- then you have weirdly unexecuted module lying around. When would A get executed?"},{"commentid":9079,"comment_count":2,"who":{"uid":"guybedford","name":"Guy Bedford"},"bug_when":"2014-06-23 12:43:55 -0700","thetext":"I can deal with this from the perspective of how the imports operate, but the bad part is not having an easy trace of how the error happened.\n\nTypically when there is an error in my code, I want to know the list of modules loaded that caused that execution to happen in the first place.\n\nIf I see an error on some third party library on a random line, that is affecting my code, I need to know why I am even running that third party library in the first place.\n\nensureEvaluated effectively has this information, as it represents a single line of execution down the module tree, this module list being the exact information the user wants to know at this point.\n\nPerhaps this is the realm of debugging tools, but it needs to be provided to the user somehow, we can't ignore debuggability."},{"commentid":9097,"comment_count":3,"who":{"uid":"johnjbarton","name":"johnjbarton"},"bug_when":"2014-06-25 07:16:49 -0700","thetext":"This example looks simply like an example of the fundamental flaw in Promises: if the dev fails to explicitly add a handler for the rejection of import B, then there is no way to know that it failed.\n\nThe example is unclear on the import of A. If by \"A is dependent on B\" means that A imports B, then if B's import throws, A's import must reject. \n\nAny preceding import of B cannot alter this result: its is not a valid module, that is what it means to throw during evaluation."},{"commentid":9100,"comment_count":4,"who":{"uid":"guybedford","name":"Guy Bedford"},"bug_when":"2014-06-25 16:39:56 -0700","thetext":"The proposal is to store modules that fail execution as \"failed\" in the module registry. And whenever another module imports from a \"failed\", module it should by default also fail and return a reject promise handler for its import as well.\n\nEnsureEvaluated does maintain an evaluation thread allowing it to report useful debugging information too.\n\nSo if I import A, which imports B, which imports C, which imports D, and D throws. We should get:\n\nSystem.import('B').catch(function(e) {\n  // e = error description, while executing D, dependency of C, dependency of B\n});\n\nThat is we can get a useful evaluation stack.\n\nThen when we import from A later, the proposal above would enable this to also error:\n\nSystem.import('A').catch(function(e) {\n  // e = Module A imports from failed module B\n});\n\nOr something potentially to that affect at least."},{"commentid":13760,"comment_count":5,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2015-03-16 14:35:23 -0700","thetext":"works as intended\n\nsee Comment #1"}]}}
---
