---
{"_attributes":{"version":"4.4.4+","urlbase":"https://bugs.ecmascript.org/","maintainer":"dherman@mozilla.com"},"bug":{"bug_id":3282,"creation_ts":"2014-10-15 04:24:00 -0700","short_desc":"12.3.5.3 step 6: throw TypeError instead of ReferenceError","delta_ts":"2014-12-07 14:34:59 -0800","product":"Draft for 6th Edition","component":"technical issue","version":"Rev 28: October 14, 2014 Draft","rep_platform":"All","op_sys":"All","bug_status":"RESOLVED","resolution":"FIXED","priority":"Normal","bug_severity":"enhancement","everconfirmed":true,"reporter":{"uid":"dslomov","name":"Dmitry Lomov"},"assigned_to":{"uid":"allen","name":"Allen Wirfs-Brock"},"long_desc":[{"commentid":10505,"comment_count":0,"who":{"uid":"dslomov","name":"Dmitry Lomov"},"bug_when":"2014-10-15 04:24:14 -0700","thetext":"For other cases where IsCallable returns false, we throw TypeError (most importantly, in GetMethod or Invoke)"},{"commentid":10652,"comment_count":1,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2014-11-16 16:23:30 -0800","thetext":"fixed in rev29editor's draft"},{"commentid":10837,"comment_count":2,"who":{"uid":"allen","name":"Allen Wirfs-Brock"},"bug_when":"2014-12-07 14:34:59 -0800","thetext":"fixed in rev29"}]}}
---
