<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [antlr-interest] Getting the exceptions caught in nextToken()
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:antlr-interest%40antlr.org?Subject=Re:%20%5Bantlr-interest%5D%20Getting%20the%20exceptions%20caught%20in%20nextToken%28%29&In-Reply-To=%3C1196798589.4755b27d6c866%40clients.latnet.lv%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="025065.html">
   <LINK REL="Next"  HREF="025109.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[antlr-interest] Getting the exceptions caught in nextToken()</H1>
    <B>Guntis Ozols</B> 
    <A HREF="mailto:antlr-interest%40antlr.org?Subject=Re:%20%5Bantlr-interest%5D%20Getting%20the%20exceptions%20caught%20in%20nextToken%28%29&In-Reply-To=%3C1196798589.4755b27d6c866%40clients.latnet.lv%3E"
       TITLE="[antlr-interest] Getting the exceptions caught in nextToken()">guntiso at latnet.lv
       </A><BR>
    <I>Tue Dec  4 12:03:09 PST 2007</I>
    <P><UL>
        <LI>Previous message: <A HREF="025065.html">[antlr-interest] Getting the exceptions caught in nextToken()
</A></li>
        <LI>Next message: <A HREF="025109.html">[antlr-interest] Getting the exceptions caught in nextToken()
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#25071">[ date ]</a>
              <a href="thread.html#25071">[ thread ]</a>
              <a href="subject.html#25071">[ subject ]</a>
              <a href="author.html#25071">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Not sure if it fits you, I use something like this:

// Error handling (do not recover).
// This part sucks, I'd prefer to call stopOnError(true) from API
// NOTE: Throwing in lexer also means: disable antlrworks debugger and lexer
syntactic predicates, Oh my dear...
@lexer::members {
public void reportError(RecognitionException e) {
    // API does not allow to throw e from here, throwing RuntimeException
instead
    throw new RuntimeException(&quot;Lexing recognition problem&quot;, e);
}
}

@members {
protected void mismatch(IntStream input, int ttype, BitSet follow)
        throws RecognitionException {
    throw new MismatchedTokenException(ttype, input);
}
public void recoverFromMismatchedSet(IntStream input, RecognitionException e,
BitSet follow)
        throws RecognitionException {
    throw e;
}
}

@rulecatch {
    catch (RecognitionException e) {
        throw e;
    }
}


&gt;<i> Currently it seems the nextToken() method in the base lexer class can
</I>&gt;<i> not be forced to throw exceptions on to the parser (or anything else)
</I>&gt;<i> -- instead the lexer is catching them and printing error messages to
</I>&gt;<i> stderr. How can these exceptions be thrown back to the parser so they
</I>&gt;<i> can be used?
</I>&gt;<i>
</I>&gt;<i> Thanks,
</I>&gt;<i> Andreas
</I>

</PRE>















<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="025065.html">[antlr-interest] Getting the exceptions caught in nextToken()
</A></li>
	<LI>Next message: <A HREF="025109.html">[antlr-interest] Getting the exceptions caught in nextToken()
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#25071">[ date ]</a>
              <a href="thread.html#25071">[ thread ]</a>
              <a href="subject.html#25071">[ subject ]</a>
              <a href="author.html#25071">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://www.antlr.org/mailman/listinfo/antlr-interest">More information about the antlr-interest
mailing list</a><br>
</body></html>
