<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [antlr-interest] Parser Generation: How to catch an exception	within an rule?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:antlr-interest%40antlr.org?Subject=Re:%20%5Bantlr-interest%5D%20Parser%20Generation%3A%20How%20to%20catch%20an%20exception%0A%09within%20an%20rule%3F&In-Reply-To=%3C358389.60574.qm%40web39506.mail.mud.yahoo.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="019644.html">
   <LINK REL="Next"  HREF="019665.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[antlr-interest] Parser Generation: How to catch an exception	within an rule?</H1>
    <B>luciano mantuaneli</B> 
    <A HREF="mailto:antlr-interest%40antlr.org?Subject=Re:%20%5Bantlr-interest%5D%20Parser%20Generation%3A%20How%20to%20catch%20an%20exception%0A%09within%20an%20rule%3F&In-Reply-To=%3C358389.60574.qm%40web39506.mail.mud.yahoo.com%3E"
       TITLE="[antlr-interest] Parser Generation: How to catch an exception	within an rule?">mantu_lists at yahoo.com.br
       </A><BR>
    <I>Mon Mar 12 05:33:33 PDT 2007</I>
    <P><UL>
        <LI>Previous message: <A HREF="019644.html">[antlr-interest] Parser Generation: How to catch an exception within an rule?
</A></li>
        <LI>Next message: <A HREF="019665.html">[antlr-interest] Parser Generation: How to catch an exception within an rule?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#19664">[ date ]</a>
              <a href="thread.html#19664">[ thread ]</a>
              <a href="subject.html#19664">[ subject ]</a>
              <a href="author.html#19664">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Thanks for answering, Luber. But i guess I don't figure out where is the insertion point of the code you mentioned... I changed my rule to this:

importDefinition
    options {defaultErrorHandler = true;}
    { boolean isStatic = false; String imp = &quot;&quot;;}
    :    
        i:&quot;import&quot;^ {#i.setType(IMPORT);} 
        ( &quot;static&quot;! {#i.setType(STATIC_IMPORT);} )? 
        imp=identifierStar SEMI! exception 
            catch[StarImportException exp]{
                syso(&quot;Error: Import star found&quot;);
            }
        
    ;

But I gain a &quot;Unhandled exception type StarImportException&quot; compilation error message. I checked the parser generated and get suprised with the code snippet corresponding to the the catch in the rule above:

catch (StarImportException exp) {
    if (inputState.guessing==0) {
        
                        syso(&quot;Error: Import star found&quot;);
                    
    } else {
        throw exp;
    }
}

I just don't understand why antlr conditionally re-throw my exception...

What am I doing wrong?


Johannes Luber &lt;<A HREF="http://www.antlr.org/mailman/listinfo/antlr-interest">jaluber at gmx.de</A>&gt; escreveu: luciano mantuaneli wrote:
&gt;<i> Greetings!
</I>&gt;<i> I have a rule called identifierStar, which throws an
</I>&gt;<i> MyOwnCheckedException exception.
</I>&gt;<i> I have another rule called importDefinition, which invokes relu x. My
</I>&gt;<i> question is how can I catch the MyOwnCheckedException exception?
</I>
Add following lines to your rule:

&gt;<i> importDefinition
</I>&gt;<i>     options {defaultErrorHandler = true;}
</I>&gt;<i>     { boolean isStatic = false; String imp = &quot;&quot;;}
</I>&gt;<i>     :    i:&quot;import&quot;^ {#i.setType(IMPORT);} ( &quot;static&quot;!
</I>&gt;<i> {#i.setType(STATIC_IMPORT);} )? imp=identifierStar SEMI!
</I>&gt;<i>     ;
</I> exception
 catch [StarImportException e] {
  System.err.println(&quot;error&quot;);
 }
&gt;<i> 
</I>&gt;<i> 
</I>&gt;<i> identifierStar returns[String result = &quot;&quot;] throws StarImportException{
</I>&gt;<i>     StringBuilder sb = new StringBuilder(&quot;&quot;);
</I>&gt;<i> }
</I>&gt;<i>     :    i:IDENT{sb.append(i.getText());}
</I>&gt;<i>         ( DOT^ i2:IDENT {sb.append(&quot;.&quot; + i2.getText());})*
</I>&gt;<i>         ( DOT^ STAR {throw new StarImportException();})?
</I>&gt;<i>         {
</I>&gt;<i>             result = sb.toString();
</I>&gt;<i>         }
</I>&gt;<i>     ;
</I>
Best regards,
Johannes Luber




Luciano Mantuaneli
Analist-Programmer
 __________________________________________________
Fale com seus amigos  de gra&#231;a com o novo Yahoo! Messenger 
<A HREF="http://br.messenger.yahoo.com/">http://br.messenger.yahoo.com/</A> 
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <A HREF="http://www.antlr.org/pipermail/antlr-interest/attachments/20070312/5ae9539c/attachment-0001.html">http://www.antlr.org/pipermail/antlr-interest/attachments/20070312/5ae9539c/attachment-0001.html</A> 
</PRE>





<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="019644.html">[antlr-interest] Parser Generation: How to catch an exception within an rule?
</A></li>
	<LI>Next message: <A HREF="019665.html">[antlr-interest] Parser Generation: How to catch an exception within an rule?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#19664">[ date ]</a>
              <a href="thread.html#19664">[ thread ]</a>
              <a href="subject.html#19664">[ subject ]</a>
              <a href="author.html#19664">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://www.antlr.org/mailman/listinfo/antlr-interest">More information about the antlr-interest
mailing list</a><br>
</body></html>
